spring:

  application:
    name: orderapi

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 1311
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

product:
  service:
    url: http://localhost:8080/product

server:
  port: 8081